apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubeconfigserver
  name: kubeconfigserver
  namespace: develop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeconfigserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kubeconfigserver
    spec:
      serviceAccountName: kubeconfigserver
      containers:
      - image: udhos/kubecloudconfigserver:0.0.0
        imagePullPolicy: Always
        name: kubecloudconfigserver
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: BACKEND
          value: http://configserver:9000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
