apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubeconfigserver
  namespace: develop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubeconfigserver
subjects:
- kind: ServiceAccount
  name: kubeconfigserver
  namespace: develop
