apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubeconfigserver
  name: kubeconfigserver
  namespace: develop
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 8080
  selector:
    app: kubeconfigserver
