apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: load-ab-parameters
  name: load-ab-parameters
  namespace: develop
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: load-ab-parameters
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: load-ab-parameters
    spec:
      containers:
      - command:
        - ab
        - -c
        - "10"
        - -n
        - "1000000"
        - http://cb-parameters:8008/v1/feature-toggles/frontend
        image: jordi/ab
        imagePullPolicy: Always
        name: ab
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
